### ISSUE TITLE
Relationships not cached

### ISSUE THREAD

**Issue by syphernl** [teepluss/laravel-precedent#1]
Queries that use the "has_many" / "belongs_to" are not being cached, even though some of them may be pretty straightforward such as:
`SELECT * FROM forum_categories ORDER BY displayorder ASC`
`SELECT * FROM forums WHERE forumcategory_id IN ('1', '2', '3', '5', '6', '7')`

Would it be possible to somehow cache these as well? We're building a rather bug application that relies a lot on relationships, caching these would greatly benefit the speed/usability.

**Comment by ammont** [comment]
I have the same problem.
